export const actionType = {
    FETCH_MOVIES: "FETCH_MOVIES",
    SELECT_MOVIE: "SELECT_MOVIE",
    DELETE_SELECTED_MOVIE: "DELETE_SELECTED_MOVIE",
    FETCH_TVSHOWS: "FETCH_TVSHOWS",
    SELECT_TVSHOWS: "SELECT_TVSHOWS",
    DELETE_SELECTED_TVSHOWS: "DELETE_SELECTED_TVSHOWS",
}